<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" 
      xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" 
      xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
      xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" 
      xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" 
      xmlns:ns0="http://xmlns.oracle.com/ParaPOCenSOA/ConsumirRunReportv1/RunReportBPELProcess" 
      xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" 
      xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" 
      xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" 
      xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns:pub="http://xmlns.oracle.com/oxp/service/PublicReportService" 
      xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
      exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 pub mhdr oraext xp20 xref socket dvm oraxsl"
      xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
      xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
      xmlns:apachesoap="http://xml.apache.org/xml-soap"
      xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RunReportBPELProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="process" namespace="http://xmlns.oracle.com/ParaPOCenSOA/ConsumirRunReportv1/RunReportBPELProcess"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/PublicReportService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="runReport" namespace="http://xmlns.oracle.com/oxp/service/PublicReportService"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED MAR 13 21:15:42 CDT 2024].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
<pub:runReport>
         <pub:reportRequest>
            <pub:attributeTemplate>Default</pub:attributeTemplate>
            <pub:attributeUILocale>en-US</pub:attributeUILocale>
            <pub:parameterNameValues>
               <pub:item>
                  <pub:name>p_subinventory</pub:name>
                  <pub:values>
                     <pub:item>
                     <xsl:value-of select="/ns0:process/ns0:subinventory"/>
                     </pub:item>
                  </pub:values>
               </pub:item>
               <pub:item>
                  <pub:name>p_organization</pub:name>
                  <pub:values>
                     <pub:item>
                     <xsl:value-of select="/ns0:process/ns0:organization"/>
                     </pub:item>
                  </pub:values>
               </pub:item>
			<pub:item>
                  <pub:name>p_item</pub:name>
                  <pub:values>
                     <pub:item>
                     <xsl:value-of select="/ns0:process/ns0:item"/>
                     </pub:item>
                  </pub:values>
               </pub:item>
			<pub:item>
                  <pub:name>p_locator</pub:name>
                  <pub:values>
                     <pub:item>
                     <xsl:value-of select="/ns0:process/ns0:locator"/>
                     </pub:item>
                  </pub:values>
               </pub:item>
            </pub:parameterNameValues>
            <pub:reportAbsolutePath>/Custom/Inventarios/Locator_On_Hand_Quantity.xdo</pub:reportAbsolutePath>
            <pub:sizeOfDataChunkDownload>-1</pub:sizeOfDataChunkDownload>
         </pub:reportRequest>
         <pub:userID>Consultor.ERP</pub:userID>
         <pub:password>R1zAcxYOcQdBV*</pub:password>
      </pub:runReport>
   </xsl:template>
</xsl:stylesheet>
