<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsumeMsgInventoryUninstallation" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/SOA_DEV/InventoryUninstallationProcess/ConsumeMsgInventoryUninstallation" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/SOA_DEV/InventoryUninstallationProcess/ConsumeMsgInventoryUninstallation" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:imp1="puntonet:oracle:ofsc" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://schemas.oracle.com/bpel/extension">
   <plt:partnerLinkType name="Consume_Message_InvUninst_plt">
      <plt:role name="Consume_Message_InvUninst_role">
         <plt:portType name="tns:Consume_Message_InvUninst_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="puntonet:oracle:ofsc" schemaLocation="oramds:/apps/soa/xsd/InputBodyIntegrationOFSC.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="Consume_Message_InvUninst_msg">
      <wsdl:part name="body" element="imp1:body"/>
   </wsdl:message>
   <wsdl:portType name="Consume_Message_InvUninst_ptt">
      <wsdl:operation name="Consume_Message_InvUninst">
         <wsdl:input message="tns:Consume_Message_InvUninst_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
